name: Deploy Lambda my-lambda-func-a

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      FUNCTION_NAME: my-lambda-func-a
      ECR_REPOSITORY: my-lambda-func-a
      IMAGE_TAG: latest
      AWS_REGION: eu-central-1
      ROLE_ARN: arn:aws:iam::794038211861:role/lambda-execution-role

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::794038211861:role/github-actions-lambda-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          ECR_REGISTRY=794038211861.dkr.ecr.${AWS_REGION}.amazonaws.com
          docker build -t $ECR_REGISTRY/${ECR_REPOSITORY}:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/${ECR_REPOSITORY}:${IMAGE_TAG}

      - name: Deploy Lambda (create or update)
        run: |
          IMAGE_URI=794038211861.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}

          if aws lambda get-function --function-name $FUNCTION_NAME --region $AWS_REGION > /dev/null 2>&1; then
            echo "Lambda function exists, updating..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --image-uri $IMAGE_URI \
              --region $AWS_REGION
          else
            echo "Lambda function does not exist, creating..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --package-type Image \
              --code ImageUri=$IMAGE_URI \
              --role $ROLE_ARN \
              --region $AWS_REGION
          fi
